/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Tue Mar 24 17:12:54 2026. */

#include "messages-tron.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const char TronGetAddress_coin_name_default[21] = "Tron";
const char TronSignTx_coin_name_default[21] = "Tron";


const pb_field_t TronGetAddress_fields[4] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, TronGetAddress, address_n, address_n, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, TronGetAddress, coin_name, address_n, &TronGetAddress_coin_name_default),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, TronGetAddress, show_display, coin_name, 0),
    PB_LAST_FIELD
};

const pb_field_t TronAddress_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, TronAddress, address, address, 0),
    PB_LAST_FIELD
};

const pb_field_t TronTransferContract_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, TronTransferContract, to_address, to_address, 0),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, TronTransferContract, amount, to_address, 0),
    PB_LAST_FIELD
};

const pb_field_t TronTriggerSmartContract_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, TronTriggerSmartContract, contract_address, contract_address, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, TronTriggerSmartContract, data, contract_address, 0),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, TronTriggerSmartContract, call_value, data, 0),
    PB_LAST_FIELD
};

const pb_field_t TronSignTx_fields[15] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, TronSignTx, address_n, address_n, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, TronSignTx, coin_name, address_n, &TronSignTx_coin_name_default),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, TronSignTx, raw_data, coin_name, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, TronSignTx, ref_block_bytes, raw_data, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, STATIC  , OTHER, TronSignTx, ref_block_hash, ref_block_bytes, 0),
    PB_FIELD(  6, UINT64  , OPTIONAL, STATIC  , OTHER, TronSignTx, expiration, ref_block_hash, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, STATIC  , OTHER, TronSignTx, contract_type, expiration, 0),
    PB_FIELD(  8, STRING  , OPTIONAL, STATIC  , OTHER, TronSignTx, to_address, contract_type, 0),
    PB_FIELD(  9, UINT64  , OPTIONAL, STATIC  , OTHER, TronSignTx, amount, to_address, 0),
    PB_FIELD( 10, MESSAGE , OPTIONAL, STATIC  , OTHER, TronSignTx, transfer, amount, &TronTransferContract_fields),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, TronSignTx, trigger_smart, transfer, &TronTriggerSmartContract_fields),
    PB_FIELD( 12, UINT64  , OPTIONAL, STATIC  , OTHER, TronSignTx, fee_limit, trigger_smart, 0),
    PB_FIELD( 13, UINT64  , OPTIONAL, STATIC  , OTHER, TronSignTx, timestamp, fee_limit, 0),
    PB_FIELD( 14, BYTES   , OPTIONAL, STATIC  , OTHER, TronSignTx, data, timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t TronSignedTx_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, TronSignedTx, signature, signature, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, TronSignedTx, serialized_tx, signature, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(TronTriggerSmartContract, data) < 65536 && pb_membersize(TronSignTx, raw_data) < 65536 && pb_membersize(TronSignTx, transfer) < 65536 && pb_membersize(TronSignTx, trigger_smart) < 65536 && pb_membersize(TronSignTx, data) < 65536 && pb_membersize(TronSignedTx, serialized_tx) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_TronGetAddress_TronAddress_TronTransferContract_TronTriggerSmartContract_TronSignTx_TronSignedTx)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for TronSignedTx.serialized_tx is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
