/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Tue Mar 24 17:12:54 2026. */

#include "messages-zcash.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ZcashSignPCZT_fields[16] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, ZcashSignPCZT, address_n, address_n, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, account, address_n, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, pczt_data, account, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, n_actions, pczt_data, 0),
    PB_FIELD(  5, UINT64  , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, total_amount, n_actions, 0),
    PB_FIELD(  6, UINT64  , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, fee, total_amount, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, branch_id, fee, 0),
    PB_FIELD(  8, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, header_digest, branch_id, 0),
    PB_FIELD(  9, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, transparent_digest, header_digest, 0),
    PB_FIELD( 10, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, sapling_digest, transparent_digest, 0),
    PB_FIELD( 11, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, orchard_digest, sapling_digest, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, orchard_flags, orchard_digest, 0),
    PB_FIELD( 13, INT64   , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, orchard_value_balance, orchard_flags, 0),
    PB_FIELD( 14, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, orchard_anchor, orchard_value_balance, 0),
    PB_FIELD( 30, UINT32  , OPTIONAL, STATIC  , OTHER, ZcashSignPCZT, n_transparent_inputs, orchard_anchor, 0),
    PB_LAST_FIELD
};

const pb_field_t ZcashPCZTAction_fields[15] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, ZcashPCZTAction, index, index, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, alpha, index, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, sighash, alpha, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, cv_net, sighash, 0),
    PB_FIELD(  5, UINT64  , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, value, cv_net, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, is_spend, value, 0),
    PB_FIELD(  7, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, nullifier, is_spend, 0),
    PB_FIELD(  8, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, cmx, nullifier, 0),
    PB_FIELD(  9, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, epk, cmx, 0),
    PB_FIELD( 10, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, enc_compact, epk, 0),
    PB_FIELD( 11, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, enc_memo, enc_compact, 0),
    PB_FIELD( 12, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, enc_noncompact, enc_memo, 0),
    PB_FIELD( 13, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, rk, enc_noncompact, 0),
    PB_FIELD( 14, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashPCZTAction, out_ciphertext, rk, 0),
    PB_LAST_FIELD
};

const pb_field_t ZcashPCZTActionAck_fields[2] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, ZcashPCZTActionAck, next_index, next_index, 0),
    PB_LAST_FIELD
};

const pb_field_t ZcashSignedPCZT_fields[3] = {
    PB_FIELD(  1, BYTES   , REPEATED, STATIC  , FIRST, ZcashSignedPCZT, signatures, signatures, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashSignedPCZT, txid, signatures, 0),
    PB_LAST_FIELD
};

const pb_field_t ZcashGetOrchardFVK_fields[4] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, ZcashGetOrchardFVK, address_n, address_n, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, ZcashGetOrchardFVK, account, address_n, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, ZcashGetOrchardFVK, show_display, account, 0),
    PB_LAST_FIELD
};

const pb_field_t ZcashOrchardFVK_fields[4] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, ZcashOrchardFVK, ak, ak, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashOrchardFVK, nk, ak, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, ZcashOrchardFVK, rivk, nk, 0),
    PB_LAST_FIELD
};

const pb_field_t ZcashTransparentInput_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ZcashTransparentInput, index, index, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, ZcashTransparentInput, sighash, index, 0),
    PB_FIELD(  3, UINT32  , REPEATED, STATIC  , OTHER, ZcashTransparentInput, address_n, sighash, 0),
    PB_FIELD(  4, UINT64  , OPTIONAL, STATIC  , OTHER, ZcashTransparentInput, amount, address_n, 0),
    PB_LAST_FIELD
};

const pb_field_t ZcashTransparentSig_fields[3] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, ZcashTransparentSig, signature, signature, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, ZcashTransparentSig, next_index, signature, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ZcashPCZTAction, enc_memo) < 65536 && pb_membersize(ZcashPCZTAction, enc_noncompact) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ZcashSignPCZT_ZcashPCZTAction_ZcashPCZTActionAck_ZcashSignedPCZT_ZcashGetOrchardFVK_ZcashOrchardFVK_ZcashTransparentInput_ZcashTransparentSig)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for ZcashPCZTAction.enc_noncompact is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
