/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Tue Mar 24 17:12:54 2026. */

#include "messages-ton.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const char TonGetAddress_coin_name_default[21] = "Ton";
const bool TonGetAddress_bounceable_default = true;
const bool TonGetAddress_testnet_default = false;
const int32_t TonGetAddress_workchain_default = 0;
const char TonSignTx_coin_name_default[21] = "Ton";
const int32_t TonSignTx_workchain_default = 0;


const pb_field_t TonGetAddress_fields[7] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, TonGetAddress, address_n, address_n, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, TonGetAddress, coin_name, address_n, &TonGetAddress_coin_name_default),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, TonGetAddress, show_display, coin_name, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, TonGetAddress, bounceable, show_display, &TonGetAddress_bounceable_default),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, TonGetAddress, testnet, bounceable, &TonGetAddress_testnet_default),
    PB_FIELD(  6, SINT32  , OPTIONAL, STATIC  , OTHER, TonGetAddress, workchain, testnet, &TonGetAddress_workchain_default),
    PB_LAST_FIELD
};

const pb_field_t TonAddress_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, TonAddress, address, address, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, TonAddress, raw_address, address, 0),
    PB_LAST_FIELD
};

const pb_field_t TonSignTx_fields[12] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, TonSignTx, address_n, address_n, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, TonSignTx, coin_name, address_n, &TonSignTx_coin_name_default),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, TonSignTx, raw_tx, coin_name, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, TonSignTx, expire_at, raw_tx, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, TonSignTx, seqno, expire_at, 0),
    PB_FIELD(  6, SINT32  , OPTIONAL, STATIC  , OTHER, TonSignTx, workchain, seqno, &TonSignTx_workchain_default),
    PB_FIELD(  7, STRING  , OPTIONAL, STATIC  , OTHER, TonSignTx, to_address, workchain, 0),
    PB_FIELD(  8, UINT64  , OPTIONAL, STATIC  , OTHER, TonSignTx, amount, to_address, 0),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, TonSignTx, bounce, amount, 0),
    PB_FIELD( 10, STRING  , OPTIONAL, STATIC  , OTHER, TonSignTx, memo, bounce, 0),
    PB_FIELD( 11, BOOL    , OPTIONAL, STATIC  , OTHER, TonSignTx, is_deploy, memo, 0),
    PB_LAST_FIELD
};

const pb_field_t TonSignedTx_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, TonSignedTx, signature, signature, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(TonSignTx, raw_tx) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_TonGetAddress_TonAddress_TonSignTx_TonSignedTx)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for TonSignTx.raw_tx is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
