/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Tue Mar 24 17:12:54 2026. */

#include "messages-solana.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const char SolanaGetAddress_coin_name_default[21] = "Solana";
const char SolanaSignTx_coin_name_default[21] = "Solana";
const char SolanaSignMessage_coin_name_default[21] = "Solana";


const pb_field_t SolanaGetAddress_fields[4] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, SolanaGetAddress, address_n, address_n, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, SolanaGetAddress, coin_name, address_n, &SolanaGetAddress_coin_name_default),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, SolanaGetAddress, show_display, coin_name, 0),
    PB_LAST_FIELD
};

const pb_field_t SolanaAddress_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, SolanaAddress, address, address, 0),
    PB_LAST_FIELD
};

const pb_field_t SolanaTokenInfo_fields[4] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, SolanaTokenInfo, mint, mint, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, SolanaTokenInfo, symbol, mint, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, SolanaTokenInfo, decimals, symbol, 0),
    PB_LAST_FIELD
};

const pb_field_t SolanaSignTx_fields[5] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, SolanaSignTx, address_n, address_n, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, SolanaSignTx, coin_name, address_n, &SolanaSignTx_coin_name_default),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, SolanaSignTx, raw_tx, coin_name, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, SolanaSignTx, token_info, raw_tx, &SolanaTokenInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t SolanaSignedTx_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, SolanaSignedTx, signature, signature, 0),
    PB_LAST_FIELD
};

const pb_field_t SolanaSignMessage_fields[5] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, SolanaSignMessage, address_n, address_n, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, SolanaSignMessage, coin_name, address_n, &SolanaSignMessage_coin_name_default),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, SolanaSignMessage, message, coin_name, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, SolanaSignMessage, show_display, message, 0),
    PB_LAST_FIELD
};

const pb_field_t SolanaMessageSignature_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, SolanaMessageSignature, public_key, public_key, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, SolanaMessageSignature, signature, public_key, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SolanaSignTx, raw_tx) < 65536 && pb_membersize(SolanaSignTx, token_info[0]) < 65536 && pb_membersize(SolanaSignMessage, message) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SolanaGetAddress_SolanaAddress_SolanaTokenInfo_SolanaSignTx_SolanaSignedTx_SolanaSignMessage_SolanaMessageSignature)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for SolanaSignTx.raw_tx is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
