/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Tue Mar 24 17:12:54 2026. */

#ifndef PB_MESSAGES_ZCASH_PB_H_INCLUDED
#define PB_MESSAGES_ZCASH_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ZcashGetOrchardFVK {
    pb_size_t address_n_count;
    uint32_t address_n[10];
    bool has_account;
    uint32_t account;
    bool has_show_display;
    bool show_display;
/* @@protoc_insertion_point(struct:ZcashGetOrchardFVK) */
} ZcashGetOrchardFVK;

typedef PB_BYTES_ARRAY_T(32) ZcashOrchardFVK_ak_t;
typedef PB_BYTES_ARRAY_T(32) ZcashOrchardFVK_nk_t;
typedef PB_BYTES_ARRAY_T(32) ZcashOrchardFVK_rivk_t;
typedef struct _ZcashOrchardFVK {
    bool has_ak;
    ZcashOrchardFVK_ak_t ak;
    bool has_nk;
    ZcashOrchardFVK_nk_t nk;
    bool has_rivk;
    ZcashOrchardFVK_rivk_t rivk;
/* @@protoc_insertion_point(struct:ZcashOrchardFVK) */
} ZcashOrchardFVK;

typedef PB_BYTES_ARRAY_T(32) ZcashPCZTAction_alpha_t;
typedef PB_BYTES_ARRAY_T(32) ZcashPCZTAction_sighash_t;
typedef PB_BYTES_ARRAY_T(32) ZcashPCZTAction_cv_net_t;
typedef PB_BYTES_ARRAY_T(32) ZcashPCZTAction_nullifier_t;
typedef PB_BYTES_ARRAY_T(32) ZcashPCZTAction_cmx_t;
typedef PB_BYTES_ARRAY_T(32) ZcashPCZTAction_epk_t;
typedef PB_BYTES_ARRAY_T(52) ZcashPCZTAction_enc_compact_t;
typedef PB_BYTES_ARRAY_T(512) ZcashPCZTAction_enc_memo_t;
typedef PB_BYTES_ARRAY_T(564) ZcashPCZTAction_enc_noncompact_t;
typedef PB_BYTES_ARRAY_T(32) ZcashPCZTAction_rk_t;
typedef PB_BYTES_ARRAY_T(80) ZcashPCZTAction_out_ciphertext_t;
typedef struct _ZcashPCZTAction {
    bool has_index;
    uint32_t index;
    bool has_alpha;
    ZcashPCZTAction_alpha_t alpha;
    bool has_sighash;
    ZcashPCZTAction_sighash_t sighash;
    bool has_cv_net;
    ZcashPCZTAction_cv_net_t cv_net;
    bool has_value;
    uint64_t value;
    bool has_is_spend;
    bool is_spend;
    bool has_nullifier;
    ZcashPCZTAction_nullifier_t nullifier;
    bool has_cmx;
    ZcashPCZTAction_cmx_t cmx;
    bool has_epk;
    ZcashPCZTAction_epk_t epk;
    bool has_enc_compact;
    ZcashPCZTAction_enc_compact_t enc_compact;
    bool has_enc_memo;
    ZcashPCZTAction_enc_memo_t enc_memo;
    bool has_enc_noncompact;
    ZcashPCZTAction_enc_noncompact_t enc_noncompact;
    bool has_rk;
    ZcashPCZTAction_rk_t rk;
    bool has_out_ciphertext;
    ZcashPCZTAction_out_ciphertext_t out_ciphertext;
/* @@protoc_insertion_point(struct:ZcashPCZTAction) */
} ZcashPCZTAction;

typedef struct _ZcashPCZTActionAck {
    bool has_next_index;
    uint32_t next_index;
/* @@protoc_insertion_point(struct:ZcashPCZTActionAck) */
} ZcashPCZTActionAck;

typedef PB_BYTES_ARRAY_T(0) ZcashSignPCZT_pczt_data_t;
typedef PB_BYTES_ARRAY_T(32) ZcashSignPCZT_header_digest_t;
typedef PB_BYTES_ARRAY_T(32) ZcashSignPCZT_transparent_digest_t;
typedef PB_BYTES_ARRAY_T(32) ZcashSignPCZT_sapling_digest_t;
typedef PB_BYTES_ARRAY_T(32) ZcashSignPCZT_orchard_digest_t;
typedef PB_BYTES_ARRAY_T(32) ZcashSignPCZT_orchard_anchor_t;
typedef struct _ZcashSignPCZT {
    pb_size_t address_n_count;
    uint32_t address_n[10];
    bool has_account;
    uint32_t account;
    bool has_pczt_data;
    ZcashSignPCZT_pczt_data_t pczt_data;
    bool has_n_actions;
    uint32_t n_actions;
    bool has_total_amount;
    uint64_t total_amount;
    bool has_fee;
    uint64_t fee;
    bool has_branch_id;
    uint32_t branch_id;
    bool has_header_digest;
    ZcashSignPCZT_header_digest_t header_digest;
    bool has_transparent_digest;
    ZcashSignPCZT_transparent_digest_t transparent_digest;
    bool has_sapling_digest;
    ZcashSignPCZT_sapling_digest_t sapling_digest;
    bool has_orchard_digest;
    ZcashSignPCZT_orchard_digest_t orchard_digest;
    bool has_orchard_flags;
    uint32_t orchard_flags;
    bool has_orchard_value_balance;
    int64_t orchard_value_balance;
    bool has_orchard_anchor;
    ZcashSignPCZT_orchard_anchor_t orchard_anchor;
    bool has_n_transparent_inputs;
    uint32_t n_transparent_inputs;
/* @@protoc_insertion_point(struct:ZcashSignPCZT) */
} ZcashSignPCZT;

typedef PB_BYTES_ARRAY_T(64) ZcashSignedPCZT_signatures_t;
typedef PB_BYTES_ARRAY_T(32) ZcashSignedPCZT_txid_t;
typedef struct _ZcashSignedPCZT {
    pb_size_t signatures_count;
    ZcashSignedPCZT_signatures_t signatures[16];
    bool has_txid;
    ZcashSignedPCZT_txid_t txid;
/* @@protoc_insertion_point(struct:ZcashSignedPCZT) */
} ZcashSignedPCZT;

typedef PB_BYTES_ARRAY_T(32) ZcashTransparentInput_sighash_t;
typedef struct _ZcashTransparentInput {
    uint32_t index;
    ZcashTransparentInput_sighash_t sighash;
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_amount;
    uint64_t amount;
/* @@protoc_insertion_point(struct:ZcashTransparentInput) */
} ZcashTransparentInput;

typedef PB_BYTES_ARRAY_T(73) ZcashTransparentSig_signature_t;
typedef struct _ZcashTransparentSig {
    ZcashTransparentSig_signature_t signature;
    bool has_next_index;
    uint32_t next_index;
/* @@protoc_insertion_point(struct:ZcashTransparentSig) */
} ZcashTransparentSig;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ZcashSignPCZT_init_default               {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, {0, {0}}, false, 0, false, 0, false, 0, false, 0, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, 0, false, 0, false, {0, {0}}, false, 0}
#define ZcashPCZTAction_init_default             {false, 0, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, 0, false, 0, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}}
#define ZcashPCZTActionAck_init_default          {false, 0}
#define ZcashSignedPCZT_init_default             {0, {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}, false, {0, {0}}}
#define ZcashGetOrchardFVK_init_default          {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, 0}
#define ZcashOrchardFVK_init_default             {false, {0, {0}}, false, {0, {0}}, false, {0, {0}}}
#define ZcashTransparentInput_init_default       {0, {0, {0}}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, false, 0}
#define ZcashTransparentSig_init_default         {{0, {0}}, false, 0}
#define ZcashSignPCZT_init_zero                  {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, {0, {0}}, false, 0, false, 0, false, 0, false, 0, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, 0, false, 0, false, {0, {0}}, false, 0}
#define ZcashPCZTAction_init_zero                {false, 0, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, 0, false, 0, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, {0, {0}}}
#define ZcashPCZTActionAck_init_zero             {false, 0}
#define ZcashSignedPCZT_init_zero                {0, {{0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}, false, {0, {0}}}
#define ZcashGetOrchardFVK_init_zero             {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, 0}
#define ZcashOrchardFVK_init_zero                {false, {0, {0}}, false, {0, {0}}, false, {0, {0}}}
#define ZcashTransparentInput_init_zero          {0, {0, {0}}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, false, 0}
#define ZcashTransparentSig_init_zero            {{0, {0}}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ZcashGetOrchardFVK_address_n_tag         1
#define ZcashGetOrchardFVK_account_tag           2
#define ZcashGetOrchardFVK_show_display_tag      3
#define ZcashOrchardFVK_ak_tag                   1
#define ZcashOrchardFVK_nk_tag                   2
#define ZcashOrchardFVK_rivk_tag                 3
#define ZcashPCZTAction_index_tag                1
#define ZcashPCZTAction_alpha_tag                2
#define ZcashPCZTAction_sighash_tag              3
#define ZcashPCZTAction_cv_net_tag               4
#define ZcashPCZTAction_value_tag                5
#define ZcashPCZTAction_is_spend_tag             6
#define ZcashPCZTAction_nullifier_tag            7
#define ZcashPCZTAction_cmx_tag                  8
#define ZcashPCZTAction_epk_tag                  9
#define ZcashPCZTAction_enc_compact_tag          10
#define ZcashPCZTAction_enc_memo_tag             11
#define ZcashPCZTAction_enc_noncompact_tag       12
#define ZcashPCZTAction_rk_tag                   13
#define ZcashPCZTAction_out_ciphertext_tag       14
#define ZcashPCZTActionAck_next_index_tag        1
#define ZcashSignPCZT_address_n_tag              1
#define ZcashSignPCZT_account_tag                2
#define ZcashSignPCZT_pczt_data_tag              3
#define ZcashSignPCZT_n_actions_tag              4
#define ZcashSignPCZT_total_amount_tag           5
#define ZcashSignPCZT_fee_tag                    6
#define ZcashSignPCZT_branch_id_tag              7
#define ZcashSignPCZT_header_digest_tag          8
#define ZcashSignPCZT_transparent_digest_tag     9
#define ZcashSignPCZT_sapling_digest_tag         10
#define ZcashSignPCZT_orchard_digest_tag         11
#define ZcashSignPCZT_orchard_flags_tag          12
#define ZcashSignPCZT_orchard_value_balance_tag  13
#define ZcashSignPCZT_orchard_anchor_tag         14
#define ZcashSignPCZT_n_transparent_inputs_tag   30
#define ZcashSignedPCZT_signatures_tag           1
#define ZcashSignedPCZT_txid_tag                 2
#define ZcashTransparentInput_index_tag          1
#define ZcashTransparentInput_sighash_tag        2
#define ZcashTransparentInput_address_n_tag      3
#define ZcashTransparentInput_amount_tag         4
#define ZcashTransparentSig_signature_tag        1
#define ZcashTransparentSig_next_index_tag       2

/* Struct field encoding specification for nanopb */
extern const pb_field_t ZcashSignPCZT_fields[16];
extern const pb_field_t ZcashPCZTAction_fields[15];
extern const pb_field_t ZcashPCZTActionAck_fields[2];
extern const pb_field_t ZcashSignedPCZT_fields[3];
extern const pb_field_t ZcashGetOrchardFVK_fields[4];
extern const pb_field_t ZcashOrchardFVK_fields[4];
extern const pb_field_t ZcashTransparentInput_fields[5];
extern const pb_field_t ZcashTransparentSig_fields[3];

/* Maximum encoded size of messages (where known) */
#define ZcashSignPCZT_size                       296
#define ZcashPCZTAction_size                     1475
#define ZcashPCZTActionAck_size                  6
#define ZcashSignedPCZT_size                     1090
#define ZcashGetOrchardFVK_size                  68
#define ZcashOrchardFVK_size                     102
#define ZcashTransparentInput_size               99
#define ZcashTransparentSig_size                 81

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_ZCASH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
