version: 2.1
jobs:
  emulator-build-test:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          name: Update Submodules
          command: |
            git submodule update --init --recursive
      - setup_remote_docker
      - run:
          name: Emulator Tests
          command: |
            pushd ./scripts/emulator
            set +e
            docker-compose up --build firmware-unit
            docker-compose up --build bridge-tests
            docker-compose up --build python-keepkey
            set -e
            docker cp "$(docker-compose ps -q firmware-unit)":/kkemu/test-reports/. ../../test-reports/
            docker cp "$(docker-compose ps -q bridge-tests)":/kkemu/test-reports/. ../../test-reports/
            docker cp "$(docker-compose ps -q python-keepkey)":/kkemu/test-reports/. ../../test-reports/
            popd
            [ "$(cat test-reports/python-keepkey/status)$(cat test-reports/bridge-tests/status)$(cat test-reports/firmware-unit/status)" == "000" ] || exit 1
      - store_test_results:
          path: test-reports
workflows:
  version: 2
  emulator:
    jobs:
      - emulator-build-test

