/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Tue Mar 24 17:12:54 2026. */

#ifndef PB_MESSAGES_TON_PB_H_INCLUDED
#define PB_MESSAGES_TON_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TonAddress {
    bool has_address;
    char address[50];
    bool has_raw_address;
    char raw_address[70];
/* @@protoc_insertion_point(struct:TonAddress) */
} TonAddress;

typedef struct _TonGetAddress {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_coin_name;
    char coin_name[21];
    bool has_show_display;
    bool show_display;
    bool has_bounceable;
    bool bounceable;
    bool has_testnet;
    bool testnet;
    bool has_workchain;
    int32_t workchain;
/* @@protoc_insertion_point(struct:TonGetAddress) */
} TonGetAddress;

typedef PB_BYTES_ARRAY_T(1024) TonSignTx_raw_tx_t;
typedef struct _TonSignTx {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_coin_name;
    char coin_name[21];
    bool has_raw_tx;
    TonSignTx_raw_tx_t raw_tx;
    bool has_expire_at;
    uint32_t expire_at;
    bool has_seqno;
    uint32_t seqno;
    bool has_workchain;
    int32_t workchain;
    bool has_to_address;
    char to_address[50];
    bool has_amount;
    uint64_t amount;
    bool has_bounce;
    bool bounce;
    bool has_memo;
    char memo[121];
    bool has_is_deploy;
    bool is_deploy;
/* @@protoc_insertion_point(struct:TonSignTx) */
} TonSignTx;

typedef PB_BYTES_ARRAY_T(64) TonSignedTx_signature_t;
typedef struct _TonSignedTx {
    bool has_signature;
    TonSignedTx_signature_t signature;
/* @@protoc_insertion_point(struct:TonSignedTx) */
} TonSignedTx;

/* Default values for struct fields */
extern const char TonGetAddress_coin_name_default[21];
extern const bool TonGetAddress_bounceable_default;
extern const bool TonGetAddress_testnet_default;
extern const int32_t TonGetAddress_workchain_default;
extern const char TonSignTx_coin_name_default[21];
extern const int32_t TonSignTx_workchain_default;

/* Initializer values for message structs */
#define TonGetAddress_init_default               {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "Ton", false, 0, false, true, false, false, false, 0}
#define TonAddress_init_default                  {false, "", false, ""}
#define TonSignTx_init_default                   {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "Ton", false, {0, {0}}, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, "", false, 0}
#define TonSignedTx_init_default                 {false, {0, {0}}}
#define TonGetAddress_init_zero                  {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, 0, false, 0, false, 0, false, 0}
#define TonAddress_init_zero                     {false, "", false, ""}
#define TonSignTx_init_zero                      {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, {0, {0}}, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, "", false, 0}
#define TonSignedTx_init_zero                    {false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define TonAddress_address_tag                   1
#define TonAddress_raw_address_tag               2
#define TonGetAddress_address_n_tag              1
#define TonGetAddress_coin_name_tag              2
#define TonGetAddress_show_display_tag           3
#define TonGetAddress_bounceable_tag             4
#define TonGetAddress_testnet_tag                5
#define TonGetAddress_workchain_tag              6
#define TonSignTx_address_n_tag                  1
#define TonSignTx_coin_name_tag                  2
#define TonSignTx_raw_tx_tag                     3
#define TonSignTx_expire_at_tag                  4
#define TonSignTx_seqno_tag                      5
#define TonSignTx_workchain_tag                  6
#define TonSignTx_to_address_tag                 7
#define TonSignTx_amount_tag                     8
#define TonSignTx_bounce_tag                     9
#define TonSignTx_memo_tag                       10
#define TonSignTx_is_deploy_tag                  11
#define TonSignedTx_signature_tag                1

/* Struct field encoding specification for nanopb */
extern const pb_field_t TonGetAddress_fields[7];
extern const pb_field_t TonAddress_fields[3];
extern const pb_field_t TonSignTx_fields[12];
extern const pb_field_t TonSignedTx_fields[2];

/* Maximum encoded size of messages (where known) */
#define TonGetAddress_size                       83
#define TonAddress_size                          124
#define TonSignTx_size                           1306
#define TonSignedTx_size                         66

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_TON_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
