/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Tue Mar 24 17:12:54 2026. */

#ifndef PB_MESSAGES_TRON_PB_H_INCLUDED
#define PB_MESSAGES_TRON_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TronAddress {
    bool has_address;
    char address[35];
/* @@protoc_insertion_point(struct:TronAddress) */
} TronAddress;

typedef struct _TronGetAddress {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_coin_name;
    char coin_name[21];
    bool has_show_display;
    bool show_display;
/* @@protoc_insertion_point(struct:TronGetAddress) */
} TronGetAddress;

typedef PB_BYTES_ARRAY_T(65) TronSignedTx_signature_t;
typedef PB_BYTES_ARRAY_T(1024) TronSignedTx_serialized_tx_t;
typedef struct _TronSignedTx {
    bool has_signature;
    TronSignedTx_signature_t signature;
    bool has_serialized_tx;
    TronSignedTx_serialized_tx_t serialized_tx;
/* @@protoc_insertion_point(struct:TronSignedTx) */
} TronSignedTx;

typedef struct _TronTransferContract {
    bool has_to_address;
    char to_address[35];
    bool has_amount;
    uint64_t amount;
/* @@protoc_insertion_point(struct:TronTransferContract) */
} TronTransferContract;

typedef PB_BYTES_ARRAY_T(512) TronTriggerSmartContract_data_t;
typedef struct _TronTriggerSmartContract {
    bool has_contract_address;
    char contract_address[35];
    bool has_data;
    TronTriggerSmartContract_data_t data;
    bool has_call_value;
    uint64_t call_value;
/* @@protoc_insertion_point(struct:TronTriggerSmartContract) */
} TronTriggerSmartContract;

typedef PB_BYTES_ARRAY_T(1024) TronSignTx_raw_data_t;
typedef PB_BYTES_ARRAY_T(2) TronSignTx_ref_block_bytes_t;
typedef PB_BYTES_ARRAY_T(8) TronSignTx_ref_block_hash_t;
typedef PB_BYTES_ARRAY_T(256) TronSignTx_data_t;
typedef struct _TronSignTx {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_coin_name;
    char coin_name[21];
    bool has_raw_data;
    TronSignTx_raw_data_t raw_data;
    bool has_ref_block_bytes;
    TronSignTx_ref_block_bytes_t ref_block_bytes;
    bool has_ref_block_hash;
    TronSignTx_ref_block_hash_t ref_block_hash;
    bool has_expiration;
    uint64_t expiration;
    bool has_contract_type;
    char contract_type[64];
    bool has_to_address;
    char to_address[35];
    bool has_amount;
    uint64_t amount;
    bool has_transfer;
    TronTransferContract transfer;
    bool has_trigger_smart;
    TronTriggerSmartContract trigger_smart;
    bool has_fee_limit;
    uint64_t fee_limit;
    bool has_timestamp;
    uint64_t timestamp;
    bool has_data;
    TronSignTx_data_t data;
/* @@protoc_insertion_point(struct:TronSignTx) */
} TronSignTx;

/* Default values for struct fields */
extern const char TronGetAddress_coin_name_default[21];
extern const char TronSignTx_coin_name_default[21];

/* Initializer values for message structs */
#define TronGetAddress_init_default              {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "Tron", false, 0}
#define TronAddress_init_default                 {false, ""}
#define TronTransferContract_init_default        {false, "", false, 0}
#define TronTriggerSmartContract_init_default    {false, "", false, {0, {0}}, false, 0}
#define TronSignTx_init_default                  {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "Tron", false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, 0, false, "", false, "", false, 0, false, TronTransferContract_init_default, false, TronTriggerSmartContract_init_default, false, 0, false, 0, false, {0, {0}}}
#define TronSignedTx_init_default                {false, {0, {0}}, false, {0, {0}}}
#define TronGetAddress_init_zero                 {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, 0}
#define TronAddress_init_zero                    {false, ""}
#define TronTransferContract_init_zero           {false, "", false, 0}
#define TronTriggerSmartContract_init_zero       {false, "", false, {0, {0}}, false, 0}
#define TronSignTx_init_zero                     {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, 0, false, "", false, "", false, 0, false, TronTransferContract_init_zero, false, TronTriggerSmartContract_init_zero, false, 0, false, 0, false, {0, {0}}}
#define TronSignedTx_init_zero                   {false, {0, {0}}, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define TronAddress_address_tag                  1
#define TronGetAddress_address_n_tag             1
#define TronGetAddress_coin_name_tag             2
#define TronGetAddress_show_display_tag          3
#define TronSignedTx_signature_tag               1
#define TronSignedTx_serialized_tx_tag           2
#define TronTransferContract_to_address_tag      1
#define TronTransferContract_amount_tag          2
#define TronTriggerSmartContract_contract_address_tag 1
#define TronTriggerSmartContract_data_tag        2
#define TronTriggerSmartContract_call_value_tag  3
#define TronSignTx_address_n_tag                 1
#define TronSignTx_coin_name_tag                 2
#define TronSignTx_raw_data_tag                  3
#define TronSignTx_ref_block_bytes_tag           4
#define TronSignTx_ref_block_hash_tag            5
#define TronSignTx_expiration_tag                6
#define TronSignTx_contract_type_tag             7
#define TronSignTx_to_address_tag                8
#define TronSignTx_amount_tag                    9
#define TronSignTx_transfer_tag                  10
#define TronSignTx_trigger_smart_tag             11
#define TronSignTx_fee_limit_tag                 12
#define TronSignTx_timestamp_tag                 13
#define TronSignTx_data_tag                      14

/* Struct field encoding specification for nanopb */
extern const pb_field_t TronGetAddress_fields[4];
extern const pb_field_t TronAddress_fields[2];
extern const pb_field_t TronTransferContract_fields[3];
extern const pb_field_t TronTriggerSmartContract_fields[4];
extern const pb_field_t TronSignTx_fields[15];
extern const pb_field_t TronSignedTx_fields[3];

/* Maximum encoded size of messages (where known) */
#define TronGetAddress_size                      73
#define TronAddress_size                         37
#define TronTransferContract_size                48
#define TronTriggerSmartContract_size            563
#define TronSignTx_size                          2134
#define TronSignedTx_size                        1094

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_TRON_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
