/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Tue Mar 24 17:12:54 2026. */

#ifndef PB_MESSAGES_SOLANA_PB_H_INCLUDED
#define PB_MESSAGES_SOLANA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _SolanaAddress {
    bool has_address;
    char address[45];
/* @@protoc_insertion_point(struct:SolanaAddress) */
} SolanaAddress;

typedef struct _SolanaGetAddress {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_coin_name;
    char coin_name[21];
    bool has_show_display;
    bool show_display;
/* @@protoc_insertion_point(struct:SolanaGetAddress) */
} SolanaGetAddress;

typedef PB_BYTES_ARRAY_T(32) SolanaMessageSignature_public_key_t;
typedef PB_BYTES_ARRAY_T(64) SolanaMessageSignature_signature_t;
typedef struct _SolanaMessageSignature {
    bool has_public_key;
    SolanaMessageSignature_public_key_t public_key;
    bool has_signature;
    SolanaMessageSignature_signature_t signature;
/* @@protoc_insertion_point(struct:SolanaMessageSignature) */
} SolanaMessageSignature;

typedef PB_BYTES_ARRAY_T(1024) SolanaSignMessage_message_t;
typedef struct _SolanaSignMessage {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_coin_name;
    char coin_name[21];
    bool has_message;
    SolanaSignMessage_message_t message;
    bool has_show_display;
    bool show_display;
/* @@protoc_insertion_point(struct:SolanaSignMessage) */
} SolanaSignMessage;

typedef PB_BYTES_ARRAY_T(64) SolanaSignedTx_signature_t;
typedef struct _SolanaSignedTx {
    bool has_signature;
    SolanaSignedTx_signature_t signature;
/* @@protoc_insertion_point(struct:SolanaSignedTx) */
} SolanaSignedTx;

typedef PB_BYTES_ARRAY_T(32) SolanaTokenInfo_mint_t;
typedef struct _SolanaTokenInfo {
    bool has_mint;
    SolanaTokenInfo_mint_t mint;
    bool has_symbol;
    char symbol[13];
    bool has_decimals;
    uint32_t decimals;
/* @@protoc_insertion_point(struct:SolanaTokenInfo) */
} SolanaTokenInfo;

typedef PB_BYTES_ARRAY_T(1232) SolanaSignTx_raw_tx_t;
typedef struct _SolanaSignTx {
    pb_size_t address_n_count;
    uint32_t address_n[8];
    bool has_coin_name;
    char coin_name[21];
    bool has_raw_tx;
    SolanaSignTx_raw_tx_t raw_tx;
    pb_size_t token_info_count;
    SolanaTokenInfo token_info[4];
/* @@protoc_insertion_point(struct:SolanaSignTx) */
} SolanaSignTx;

/* Default values for struct fields */
extern const char SolanaGetAddress_coin_name_default[21];
extern const char SolanaSignTx_coin_name_default[21];
extern const char SolanaSignMessage_coin_name_default[21];

/* Initializer values for message structs */
#define SolanaGetAddress_init_default            {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "Solana", false, 0}
#define SolanaAddress_init_default               {false, ""}
#define SolanaTokenInfo_init_default             {false, {0, {0}}, false, "", false, 0}
#define SolanaSignTx_init_default                {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "Solana", false, {0, {0}}, 0, {SolanaTokenInfo_init_default, SolanaTokenInfo_init_default, SolanaTokenInfo_init_default, SolanaTokenInfo_init_default}}
#define SolanaSignedTx_init_default              {false, {0, {0}}}
#define SolanaSignMessage_init_default           {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "Solana", false, {0, {0}}, false, 0}
#define SolanaMessageSignature_init_default      {false, {0, {0}}, false, {0, {0}}}
#define SolanaGetAddress_init_zero               {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, 0}
#define SolanaAddress_init_zero                  {false, ""}
#define SolanaTokenInfo_init_zero                {false, {0, {0}}, false, "", false, 0}
#define SolanaSignTx_init_zero                   {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, {0, {0}}, 0, {SolanaTokenInfo_init_zero, SolanaTokenInfo_init_zero, SolanaTokenInfo_init_zero, SolanaTokenInfo_init_zero}}
#define SolanaSignedTx_init_zero                 {false, {0, {0}}}
#define SolanaSignMessage_init_zero              {0, {0, 0, 0, 0, 0, 0, 0, 0}, false, "", false, {0, {0}}, false, 0}
#define SolanaMessageSignature_init_zero         {false, {0, {0}}, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define SolanaAddress_address_tag                1
#define SolanaGetAddress_address_n_tag           1
#define SolanaGetAddress_coin_name_tag           2
#define SolanaGetAddress_show_display_tag        3
#define SolanaMessageSignature_public_key_tag    1
#define SolanaMessageSignature_signature_tag     2
#define SolanaSignMessage_address_n_tag          1
#define SolanaSignMessage_coin_name_tag          2
#define SolanaSignMessage_message_tag            3
#define SolanaSignMessage_show_display_tag       4
#define SolanaSignedTx_signature_tag             1
#define SolanaTokenInfo_mint_tag                 1
#define SolanaTokenInfo_symbol_tag               2
#define SolanaTokenInfo_decimals_tag             3
#define SolanaSignTx_address_n_tag               1
#define SolanaSignTx_coin_name_tag               2
#define SolanaSignTx_raw_tx_tag                  3
#define SolanaSignTx_token_info_tag              4

/* Struct field encoding specification for nanopb */
extern const pb_field_t SolanaGetAddress_fields[4];
extern const pb_field_t SolanaAddress_fields[2];
extern const pb_field_t SolanaTokenInfo_fields[4];
extern const pb_field_t SolanaSignTx_fields[5];
extern const pb_field_t SolanaSignedTx_fields[2];
extern const pb_field_t SolanaSignMessage_fields[5];
extern const pb_field_t SolanaMessageSignature_fields[3];

/* Maximum encoded size of messages (where known) */
#define SolanaGetAddress_size                    73
#define SolanaAddress_size                       47
#define SolanaTokenInfo_size                     55
#define SolanaSignTx_size                        1534
#define SolanaSignedTx_size                      66
#define SolanaSignMessage_size                   1100
#define SolanaMessageSignature_size              100

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_SOLANA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
